name: Release Nightly

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.12'
    - name: Prepare nightly
      run: .github/workflows/nightly.sh
    - name: Get current version
      id: version
      run: echo "::set-output name=version::$(jq -r .version package.json)"
    - name: Install dependencies
      run: |
        npm install
        npm install -g vsce
        npm install -g npx
    - name: Build
      run: |
        npm run vscode:prepublish
        vsce package
    - name: Check
      run: |
        npm run lint
        npm test --silent
    - name: Publish to Marketplace
      run: vsce publish --pat "${{ secrets.VSCODE_MARKETPLACE_TOKEN }}"
    - name: Publish to Open VSX
      run: npx ovsx publish "vscode-tlaplus-nightly-${{ steps.version.outputs.version }}.vsix" -p "${{ secrets.OPEN_VSX_TOKEN }}"
